# Site settings
title: Code Time with Hannah
header-img: img/home-bg.png
email: hecarnes@gmail.com
copyright_name: hcarnes
description: > # this means to ignore newlines until "baseurl:"
  Learning through Flatiron School's Online Web Developer Program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: KetoAustin
github_username:  hcarnes
learn_profile: hcarnes
email_username: hecarnes@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
