# Site settings
title: Code Time
header-img: img/home-bg.png
email: hecarnes@gmail.com
copyright_name: hcarnes
description: > # this means to ignore newlines until "baseurl:"
  Adventures in learning full-stack development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: KetoAustin
github_username:  hcarnes
learn_profile: hcarnes
email_username: hecarnes@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
